import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import { AudioProvider } from "@/components/AudioContext";
import { Suspense } from "react";
import dynamic from 'next/dynamic'

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

const VoiceWave = dynamic(() => import("@/components/VoiceWave"), { 
  ssr: false,
  loading: () => <div className="h-[90px]" />
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <AudioProvider>
          <div className="relative min-h-screen flex flex-col">
            <Suspense>
              <Header className="relative z-30" />
            </Suspense>
            <Suspense fallback={null}>
              <main className="flex-1 relative z-10">
                <PageTransition>
                  <StairTransition />
                  {children}
                </PageTransition>
              </main>
            </Suspense>
            <Suspense fallback={<div className="h-[90px]" />}>
              <VoiceWave />
            </Suspense>
          </div>
        </AudioProvider>
      </body>
    </html>
  );
}